---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: kosik789/project_2:db
   ports:
     - "3306:3306"

 application:
   container_name: appcontainer
   image: kosik789/project_2:app_pro
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
